### ISSUE TITLE
NextJS 13: support for server-side components

### ISSUE THREAD

**Issue by schehata** [axiomhq/next-axiom#108]
# Describe the problem you'd like to have solved

I would like to update next-axiom to be able to handle the new server-side components from NextJS 13.

# Describe the ideal solution

Still investigating

**Comment by AnandChowdhary** [comment]
Related question: Can I use next-axiom with a Next.js v13 app using the app directory, even if server components aren't fully supported? Or would you recommend waiting until this is implemented? Thanks!

**Comment by schehata** [comment]
Hi @AnandChowdhary , you can still use next-axiom with your app, the API (lambda and Edge) functions will still work. You can use the logger in your components and call `await log.flush()` to ensure delivery of your logs. 

web-vitals will not work so far in Next 13, but there is already an open PR to make that work. Support for next 13 will improve gradually.

**Comment by tavaneftekhar** [comment]
Is there an ETA for when server-side and client-side components in the app directory may be supported?

**Comment by schehata** [comment]
@tavaneftekhar I believe the client-side components should work without a problem. The one that would have a problem is probably the server-side components. It's still in discovery phase, so that might take a while.

**Comment by schehata** [comment]
@tavaneftekhar hmmm that shouldn't happen. If you have configured the environment variables, `log.info` and `await log.flush()` should be enough.  I will take a look today and let you know.

**Comment by schehata** [comment]
@tavaneftekhar I have tried next-axiom on a fresh next13 project, it works fine on components inside the `app` directory. If you don't configure the required environment variables, logs will print to console. if on vercel, and integration is enabled, you would see the logs in the axiom log stream.

**Comment by bahlo** [comment]
Hey everyone, this is working now! Please check out `1.0.0-rc.1` and refer to the current README for instructions. If you run into issues, def. let us know 🙏
