### ISSUE TITLE
[Question] How (if possible) can I configure the environment field in Vercel logs? 

### ISSUE THREAD

**Issue by ohager** [axiomhq/next-axiom#113]
So, I managed to log our staging environment (by enabling the `NEXT_PUBLIC_AXIOM_INGEST_ENDPOINT` var for Preview environment), but in the logs still states `environment: 'production'`.

![image](https://user-images.githubusercontent.com/3920663/220368494-78653e89-ebc8-47e4-9fc9-f9503814c771.png)

Although, I imagine that this is all about the `VERCEL_ENV` Env var, is their another/alternative way to configure the environment? 

> This seems a bit related to #55

**Comment by ohager** [comment]
Closed as I may have looked wrongly.... I'm seeing the correct environment now:

![image](https://user-images.githubusercontent.com/3920663/220388871-98a8a03a-8dce-48f4-b863-171749a72b58.png)


All fine!

**Comment by schehata** [comment]
all good, glad it worked out by itself.

**Comment by DasOhmoff** [comment]
I have this exact issue. And the environment variable fields does not seem to get updated to the correct value:
![image](https://github.com/axiomhq/next-axiom/assets/16063186/26cb103d-c61f-4a58-8414-4b703d4e9989)
