### ISSUE TITLE
403 on Vercel

### ISSUE THREAD

**Issue by lvilasboas-dti** [axiomhq/next-axiom#115]
Hello everyone,

I'm using:
- next@12.3.3
- react@17 (unfortunately, we're using a must-have dependency that only works on react 17)
- next-axiom@0.17.0

My application is being deployed to Vercel.
I've setup the integration with Axiom (it was as seamless as they come, indeed), the environment variable was created automatically, and Axiom started ingesting data (server-side logs, etc).
Then I moved to using the `withAxiom` HOC, in order to enable client-side `log` and `reportWebVitals`.

But, whenever those trigger, I can see a 403 error:
![image](https://user-images.githubusercontent.com/81981018/229186691-db72c6ab-039b-49d8-83d8-b41b9071802f.png)
Both requests hit this url: `https://<my-domain>/_axiom/<web-vitals|logs>`

And the response (for either) is an empty object:
![image](https://user-images.githubusercontent.com/81981018/229187370-3b7c48e6-d01a-4b4c-a4e8-a99371e0053a.png)

Can anyone help me shed some light on this?
Thank you!

**Comment by odcey** [comment]
Getting the exact same problem

**Comment by adpadillar** [comment]
Same issue here.

`https://my.public.url/_axiom/web-vitals` comes back with 403 Forbidden code

**Comment by adpadillar** [comment]
> I guess the custom logger is not working but the withAxiom interceptor can log
> Also tested without being in the browser, but in the nextjs api, and the log is not present too

*I THINK* that if you have the vercel integration the `withAxiom(config)` isn't actually necessary to log the requests (the 403 you mention) in their dashboard. The integration takes the logs from vercel directly

**Comment by schehata** [comment]
@odcey are you trying on a production deployment or a preview one? have you added any env variables to vercel settings? there should be a `NEXT_PUBLIC_AXIOM_INGEST_ENDPOINT` that is enabled by default for production.

**Comment by schehata** [comment]
> > I guess the custom logger is not working but the withAxiom interceptor can log
> > Also tested without being in the browser, but in the nextjs api, and the log is not present too
> 
> _I THINK_ that if you have the vercel integration the `withAxiom(config)` isn't actually necessary to log the requests (the 403 you mention) in their dashboard. The integration takes the logs from vercel directly.
> 
> If what I'm saying is true, then the logs showing up doesn't actually mean `withAxiom` is working and the logger isn't

the integrations has 2 parts, one is the log drain, which basically sends any console.log output from api functions to axiom. and the other part is `withAxiom` and the logger which sends custom logs from both backend and frontend.

**Comment by odcey** [comment]
> @odcey are you trying on a production deployment or a preview one? have you added any env variables to vercel settings? there should be a `NEXT_PUBLIC_AXIOM_INGEST_ENDPOINT` that is enabled by default for production.


@schehata yes I have this env variable, it was added automatically to Vercel with production checked

**Comment by lvilasboas-dti** [comment]
I can confirm that my deployment is a production one as well, with the env variable that was set automatically when I set up the integration

**Comment by schehata** [comment]
I confirm that I am able to reproduce. I will take a look on why this might be happening and get back to you.

**Comment by garmeeh** [comment]
Same here.

- Log drain works as expected
- Custom logs are giving 403 that I can see in Vercel logs

**Comment by evanrooijen** [comment]
Any progress?

**Comment by bahlo** [comment]
Hey, this has high priority for us so expect an update in the next days 👍

**Comment by bahlo** [comment]
Hey everyone, we found the bug and fixed it on our side! Very sorry for the inconvenience — feel free to reopen if you still experience this issue :v:

**Comment by matthewlilley** [comment]
@bahlo Our front-end logs are missing too, endpoint https://www.sushi.com/_axiom/logs is returning 403. We are on the latest next-axiom and next.js 13.3.1.

**Comment by sighash256** [comment]
same with us. I'm also getting 403. I'm using 
```
    "next": "13.4.12",
    "next-axiom": "^1.0.0-rc.1",
```

**Comment by bahlo** [comment]
@matthewlilley @sighash256 Sorry you're running into this. Did you recently upgrade the Vercel plan or had a member leave the org? Can you try reinstalling the Vercel integration and redeploying?

**Comment by matthewlilley** [comment]
@bahlo @sighash256 this happens when field limits are reached. It isn't ideal because logs just stop getting recorded and there's no real way to manage fields. One update of logging structure can cause all new logs to get lost.

**Comment by bahlo** [comment]
@matthewlilley Oh, that's interesting! We're actively working on improving the experience around reaching field limits right now.

Nonetheless this shouldn't be a 403, looking into that (internal issue #: AXM-1468)
