### ISSUE TITLE
[Question] Adding custom fields to request logs

### ISSUE THREAD

**Issue by b0o** [axiomhq/next-axiom#123]
Is it possible to add a custom field to all request logs? 

We are running behind Cloudflare and would like to include the value of `cf-connecting-ip` in our logs. 

We could do this in our middleware by manually logging the value, but I'm wondering if there's a way to get the IP included in the logs that are automatically output by Next/Vercel on request.

**Comment by schehata** [comment]
hi @b0o , you can create a child of a logger with the args you want, and the args will be attached to every log record. for example:

```ts
func handler(req) {
  const log = req.log.with({cloudflareIP: 'someValue'})
  
  log.info('something')
  ...
}

export default withAxiom(handler)
```

the output of this will be something like:

```
{'message': 'something', 'fields': {'cloudflareIP': 'someValue'}}
```

**Comment by bahlo** [comment]
@b0o Another option would be to wrap `withAxiom` in a custom function that adds these fields to the logger. Please re-open if your issue remains unsolved 😌
