### ISSUE TITLE
How do I configure the log fields and values?

### ISSUE THREAD

**Issue by travistylerVII** [axiomhq/next-axiom#126]
How do I add, remove and configure field values when logging? 

I would like to change the platform source to "Back-end" and add a path field. 

![CleanShot 2023-06-21 at 16 30 47@2x](https://github.com/axiomhq/next-axiom/assets/4889865/29bace0a-981e-4eef-9cf7-b7ba23c48085)

**Comment by bahlo** [comment]
Hi @travistylerVII, you cannot override the platform values at the moment.

I recommend using your own field for that, you can attach fields to a logger like this:
```typescript
const log = req.log.with({ source: 'back-end' });
```

It will then show up as `fields.source`.

Please reopen this issue if this doesn't solve this to your satisfaction.
