### ISSUE TITLE
Is it possible to disable ingesting Vercel's log drains?

### ISSUE THREAD

**Issue by lvilasboas-dti** [axiomhq/next-axiom#131]
I'm implementing Axiom logs on my application, but for backwards compatibility, I'll keep on using Vercel's logs for a while.

I have a logging layer that logs into Vercel and now will also log into Axiom, but if I keep it like this, my logs will be duplicated, since Axiom ingests Vercel's log drains.

So, is there a way where I can disable Axiom from also pulling the log drains?

**Comment by schehata** [comment]
maybe you can disable the integration if you are not going to use it. you can then create a token and export it through vercel settings. We haven't tested this use-case ourselves but should work.
