### ISSUE TITLE
Vitals Dashboard

### ISSUE THREAD

**Issue by focux** [axiomhq/next-axiom#138]
I don't think this is the right place to post this feedback but I didn't know where to do it, so sorry for creating an issue for this.

It would be good to have a way to create/import a dashboard template for Vitals like the one you have for Vercel's integration without having to create all the graphs and stats manually. It would help a lot the people like me who are not hosting his Next.js app on Vercel.

**Comment by schehata** [comment]
hey @focux, thanks for your feedback! I hear you, absolutely right. We have this on our roadmap, a more better way to create and import dashboards, I can't promise you a timeline yet, but I will take your feed directly to my team and make sure its heard.

btw, we have a [discord community](https://axiom.co/discord), you can jump in for feedback and questions, we would appreciate it a lot. thx!

**Comment by focux** [comment]
Awesome, thank you, and also good to know that you have a discord, I will use it next time if I have more feedback/questions.
