### ISSUE TITLE
Fix type of `Logger.flush()`

### ISSUE THREAD

**Issue by Burry** [axiomhq/next-axiom#150]
The Logger class' `flush` method has an `any` type, making my `typescript-eslint` configuration scream at me. I'd recommend allowing TypeScript to just infer types whenever possible and remove the `any` type here.

https://github.com/axiomhq/next-axiom/blob/9ec2a795b5d5e84b683c117e3a5058fb72573676/src/logger.ts#L197-L199

**Comment by ImLunaHey** [comment]
Seems like this would be a better option as there's no real reason to return anything from the `flush` method.

```ts
 flush = async () => { 
   await Promise.all([this.sendLogs(), ...this.children.map((c) => c.flush())]); 
 }; 
 ```
