### ISSUE TITLE
"next-axiom" has no exported member named 'reportWebVitals'. Did you mean 'useReportWebVitals'?

### ISSUE THREAD

**Issue by maxmandia** [axiomhq/next-axiom#154]
Can't find the correct exported member - is the documentation outdated?

**Comment by evandeam** [comment]
@zoul It looks like the `useReportWebVitals` function is actually from `'next/web-vitals'`, not `next-axiom`. Confusing naming, though, that both Next and Axiom would have functions for similar purposes that are named exactly the same.

I still haven't found anything that clears this issue up.

**Comment by zoul** [comment]
To me it looks as though `next-axiom` just re-exports the `useReportWebVitals` function from `next/web-vitals`, [see here](https://github.com/axiomhq/next-axiom/blob/828c22ee355788fef4d66fb8d170043cf62509c8/src/webVitals/index.ts#L2). So it’s not two different functions under the same name, but one. Makes sense, maybe they want to customize the code for Axiom later without changing the API.

**Comment by schehata** [comment]
@zoul you nailed it. The `useReportWebVitals` hooks was added to Next.js as a contribution from Axiom. We use it but we provide the current pathname to the values before sending those data to Axiom. We used the same name to be consistent.

**Comment by schehata** [comment]
> @zoul It looks like the `useReportWebVitals` function is actually from `'next/web-vitals'`, not `next-axiom`. Confusing naming, though, that both Next and Axiom would have functions for similar purposes that are named exactly the same.
> 
> I'm working on a project that still uses the Pages router, but [this link](https://github.com/axiomhq/next-axiom#web-vitals) makes it look like the API is now just a component that you add to your layout.tsx (if you're using the App router).
> 
> Unclear if one would add this to their _app or _document file if using the Pages router.

The current version supports the App navigation method, for the legacy navigation you could fallback for [v0.18.0](https://www.npmjs.com/package/next-axiom/v/0.18.0) If I recall correctly.
