### ISSUE TITLE
withAxiom() route wrapper doesn't parse fields

### ISSUE THREAD

**Issue by rajdtta** [axiomhq/next-axiom#160]
```ts
export const POST = withAxiom(async (req: AxiomRequest) => {
  const ENDPOINT_LOGGER = req.log.with({
    endpoint: {
      route: "/api/dashboard",
      method: "POST",
      searchParams: req.nextUrl.searchParams.toString(),
    },
  });
  
  ENDPOINT_LOGGER.info("test");
...
}
```

When wrapping my route handlers with `withAxiom()`, I would expect for the args (`endpoint.route`, etc.) to be their own fields within Axiom. However, the args seem to be being parsed as part of the message (instead of being split into their own field).

<img src="https://i.raj.wtf/imgs/DDAvkDXUXGVKVpcFp6owV4IORFA.png" />

**Comment by bahlo** [comment]
Hey @rajdtta, that's the console output for preview/development environments, picked up by the log sink. On production this should be sent to Axiom directly. What environment are you seeing this on?

**Comment by rajdtta** [comment]
> Hey @rajdtta, that's the console output for preview/development environments, picked up by the log sink. On production this should be sent to Axiom directly. What environment are you seeing this on?

Sorry, just seeing this now. This is indeed on a development / preview environment
