### ISSUE TITLE
next-axiom is blocking our ability to upgrade to Next 14

### ISSUE THREAD

**Issue by julienben** [axiomhq/next-axiom#165]
Hey there!

My team and I are Axiom users and have been enjoying the platform a lot so far.

There's one major issue we have right now that I'll try to explain in a few short points:

- We use the pages router in Next.js (currently on v13).
- As far as I can tell, next-axiom 0.19.0 and above only supports the app router, not the pages router. (Am I wrong about this?)
- The `peerDeps` in next-axiom 0.18.0 only allow Next up to version 13, not 14.

In order to be able to migrate to Next 14 without a dependency conflict, we would need a version of next-axiom which supports Next 14 and the pages router simultaneously. Maybe a 0.18.1.

Is that something you can help us with? 

Thanks in advance for any help!

**Comment by schehata** [comment]
hey @julienben , thanks for reaching out. We are working on it at the moment, there is an almost ready PR. Will release as soon its ready.

**Comment by c-ehrlich** [comment]
v0.18.1 is ready with support for Next 14 with the Pages router :)

**Comment by julienben** [comment]
Thanks a lot for this!! Really appreciate it!
