### ISSUE TITLE
Why not directly send to axiom endpoint on browser

### ISSUE THREAD

**Issue by Jokcy** [axiomhq/next-axiom#172]
https://github.com/axiomhq/next-axiom/blob/ba5dedce6a4100bcee7d4ada078a36b4c5a68941/src/platform/generic.ts#L27

Based on this line, borwser logs will send to next server then next server will send to axiom.

This is redundant because:

1. the token is still exposed
2. directly send to axiom work fine, no CORS issue
3. a bunch of requests will be used in this solution, requests means money

**Comment by Jheesbrough** [comment]
I believe this is to proxy request so there are not blocked by in browser ad blocks.

**Comment by Jokcy** [comment]
> I believe this is to proxy request so there are not blocked by in browser ad blocks.

I don't think this should be such a high priority issue.

**Comment by Jheesbrough** [comment]
It's a feature of the logging library, not an issue.

**Comment by Jokcy** [comment]
Then why sdks of sentry or mux they directly send request from client?

**Comment by bahlo** [comment]
Hey, requests are proxied for two reasons:

1. Requests will get blocked (you can see this with other Web Vitals or analytics libraries that send directly)
2. The proxy extends the Web Vitals to add geo information.

@Jokcy would you prefer an option to send directly to us? 
Feel free to re-open, closing for now.
