### ISSUE TITLE
Is the pages router supported in the latest version with web vitals?

### ISSUE THREAD

**Issue by DasOhmoff** [axiomhq/next-axiom#177]
Hello, thanks for helping me out :)

is the pages router supported on the latest version and with web vitals? I am asking because the documentation says:
```
Note Using the Pages Router? Use version 0.*, which will continue to get security patches. Here's the [README for 0.x](https://github.com/axiomhq/next-axiom/blob/v0.x/README.md).
```

But the github issues seems to suggest otherwise? Also I tested the latest version with the pages router and web vitals and it SEEMS to be working?

Thanks again!

**Comment by schehata** [comment]
oh, I think that should be 'Not using the App router?'. 

The latest version of next-axiom is designed for app router, so can't guarantee that it works properly for pages router, we have the `0.x` versions to keep support for it.

**Comment by DasOhmoff** [comment]
Ok, I see. So is the 0.x version guaranteed to support it?
