### ISSUE TITLE
What value for NEXT_PUBLIC_AXIOM_INGEST_ENDPOINT

### ISSUE THREAD

**Issue by astanciu** [axiomhq/next-axiom#191]
Trying to test sending logs from local dev environment, all the docs and issues talk about setting `NEXT_PUBLIC_AXIOM_INGEST_ENDPOINT` but no mention of what value this should be set to.

What should this value be set to?
And can someone please confirm this will allow me to send logs from my local dev env, not vercel.

**Comment by astanciu** [comment]
I think the value should be `https://api.axiom.co/api/v1/datasets/DATASETNAME/ingest`

Please correct me if I'm wrong. 


I've set this var and I still am not able to see any events in development. I do see it in Vercel preview env, where the var is also set. My test is a manual log.info() using useLogger();

**Comment by schehata** [comment]
You can remove this var if you are not using Vercel integration, normally you would use `AXIOM_URL` instead but it has a default value, so you can just add `AXIOM_TOKEN` and `AXIOM_DATASET` and should be good to go.

**Comment by astanciu** [comment]
Solved. The value is automatically generated and inserted when the vercel integration is set up. One must copy the env var + value from Vercel if needed.
