### ISSUE TITLE
The remeda dependency

### ISSUE THREAD

**Issue by LufyCZ** [axiomhq/next-axiom#197]
It is only used in [one place](https://github.com/axiomhq/next-axiom/blob/50053d764f66e5866c7414e5eff9f489311e2a7a/src/util.ts#L7) for the `equals` function and it [increases bundle size by 200%](https://bundlephobia.com/package/next-axiom@1.3.0).

Since `useDeepMemo` is used to deeply check objects, re-using something like [https://www.npmjs.com/package/use-deep-compare](https://www.npmjs.com/package/use-deep-compare) (at just 732B gzipped) might make a bit more sense.

**Comment by c-ehrlich** [comment]
Solved in #198, new minor version coming :)
