### ISSUE TITLE
405 (Method Not Allowed) on web vitals

### ISSUE THREAD

**Issue by pepew-le-boss** [axiomhq/next-axiom#213]
I'm using the NextJS integration and the `withAxiom()` function. 

I can see all my logs in the axiom dashboard in production however each time I navigate to a page on my website I get this error in the console: `POST https://www.my-website.com/fr/_axiom/web-vitals 405 (Method Not Allowed)`

Is this because I add the `[lang]` param in the url ?

**Comment by schehata** [comment]
yeah, perhaps that's the issue. You can try to build your rewrites object in a way that respects the language path. This is the one we provide with next-axiom: https://github.com/axiomhq/next-axiom/blob/c1b8e117d80d7fb4c8df7e69d059970ba837c0ee/src/withAxiom.ts#L26

**Comment by pepew-le-boss** [comment]
Because it's my middleware redirecting for internationalization purposes I just excluded the `_axiom` path in the matcher:
`matcher: ["/((?!api|_next/static|_next/image|images|favicon.ico|_axiom).*)"]`

A lot easier than messing with rewrites 😂
