### ISSUE TITLE
next-axiom should not treat NEXT_REDIRECT as errors

### ISSUE THREAD

**Issue by empz** [axiomhq/next-axiom#219]
When wrapping route handlers with `withAxiom`, redirects using App Router's redirect() are caught and treated as errors. If this library claims to be compatible with the App Router, it should understand this is not an error. Same thing with notFound().

By the way, is this being maintaned at all? Last release was months ago.

**Comment by schehata** [comment]
Hi, @empz thanks for you feedback. Yes next-axiom is very much active, there has not been changes in a while thats why there was no releases. We are planning a release soon with the changes from #218, I will also take the bug you mentioned into account.

**Comment by ReDev1L** [comment]
> Hi, @empz thanks for you feedback. Yes next-axiom is very much active, there has not been changes in a while thats why there was no releases. We are planning a release soon with the changes from #218, I will also take the bug you mentioned into account.

Hi, those errors and status code overriding affects DX seriously, any plans to fix that?
https://github.com/axiomhq/next-axiom/blob/main/src/withAxiom.ts#L131-L151

**Comment by dasfmi** [comment]
I have created a PR to catch `NEXT_NOT_FOUND` and `NEXT_REDIRECT` to handle the status codes, but not sure what is the expect type of the log, its currently still an `error`, what's your thoughts on this?

also, is there any other catch errors we should catch?

**Comment by dasfmi** [comment]
updated my PR with default values for both errors and a way to override those values through the config object.
