### ISSUE TITLE
`withAxiom` does not support next.js' `basePath`

### ISSUE THREAD

**Issue by klapec** [axiomhq/next-axiom#29]
I have my next.js app set up with the `basePath` option meaning that it's running on example.com/foo instead of example.com. Unfortunately, `withAxiom` sets up its endpoints in a way that does not seem to support `basePath`:
```typescript
source: `${proxyPath}/web-vitals`,
```
where `proxyPath` = `export const proxyPath = '/_axiom';`.

I can see in the devtools' network tab that the request is being fired at `example.com/_axiom/web-vitals`. Would it be possible to support the `basePath` option so that axiom's requests would be fired at, e.g., `example.com/foo/_axiom/web-vitals`?

**Comment by schehata** [comment]
hi @klapec, let me check this out and get back to you. sorry for the late response, for some reason I didn't see the issue when it was created.

**Comment by schehata** [comment]
looks like there is no easy way to get the basePath outside nextConfig or with `useRouter`. I think the easiest way is to add `basePath: false` in our rewrites.

**Comment by schehata** [comment]
I have create a PR #46, and it worked 🥳

**Comment by klapec** [comment]
Woohoo! Awesome, thank you! 🥳

**Comment by schehata** [comment]
hey @klapec, we have merged the PR, but for some reason the ci job to publish the package to npm is skipped, I will figure it out tomorrow.

**Comment by klapec** [comment]
Alright, thanks for the heads up! I appreciate it. I'll check it tomorrow then.

**Comment by klapec** [comment]
Thanks for the release! Unfortunately I don't think it works or perhaps I'm doing something wrong.
Here's an example app for reproduction: https://github.com/klapec/next-axiom-basepath
I have `next-axiom` at `^0.12.1` and still it calls `/_axiom/web-vitals`, ignoring the basePath (here it's `/prefix`):
<img width="853" alt="Zrzut ekranu 2022-08-10 o 11 42 32" src="https://user-images.githubusercontent.com/565022/183870672-215ac29f-8a0f-45a5-9701-8bcea4534264.png">

**Comment by schehata** [comment]
@klapec The fix that I did, is that the rewrite should ignore the basePath, so that when `/_axiom` it would work properly. from the screenshot I see that response 200, can you check if you received the webvitals report or logs in axiom?

**Comment by klapec** [comment]
I wonder whether it matters that it's running on localhost vs a "real" domain? I have a production app running on `example.com/prefix/` (nginx rewrites that url to vercel) and I can imagine that a request to `example.com/_axiom/web-vitals` would end up with a 404.

**Comment by klapec** [comment]
Haven't checked that though on production. I could either do that or spin up a local nginx instance that replicates my production setup.

**Comment by klapec** [comment]
Answering your question whether I've received the report in axiom - yes, it works correctly. I'll test it on a production environment (😈) and I'll get back to you. Thanks! :)

**Comment by schehata** [comment]
that sounds like good news 😂 my only concern  (on production) would be if that `/_axiom` goes to nginx first, then nginx wouldn't rewrite it correctly. but I am assuming after the nginx rewrite, vercel should be able to handle its rewrites correctly.

**Comment by klapec** [comment]
Yeah, looks like an nginx rewrite from `/_axiom` to `/prefix/axiom` is going to be necessary.

**Comment by klapec** [comment]
Either way - that's not the scope of this fix, we can assume it's working fine :) Thanks again for your help!

**Comment by schehata** [comment]
hmmm I don't think that would work with the current solution. Nextjs won't know what to do with `/basePath/_axiom` because it expects `/_axiom` directly. I am thinking maybe a proxy_pass is needed in nginx, to pass /_axiom to `your_next_js/_axiom`.

**Comment by klapec** [comment]
Yeah, you're right, it's going to be a proxy_pass from `/_axiom` to `my_vercel_deployment/_axiom`.
