### ISSUE TITLE
Getting occasional 404s for _axiom/web-vitals call on PROD

### ISSUE THREAD

**Issue by jerang** [axiomhq/next-axiom#52]
Noticed my production dashboard is showing a small percentage of 404 errors for the web vitals call. Any idea what's causing this and how I can patch it? I do see the web vitals working since there are a number of successful calls for most users.

Secondly, is there a way to get this call to work locally?

**Comment by bahlo** [comment]
Hey @jerang, thanks for the issue -- it's something we're aware of and looking into 👍 

> Secondly, is there a way to get this call to work locally?

You can copy the `NEXT_PUBLIC_AXIOM_INGEST_ENDPOINT` from your environment and expose it locally.

**Comment by agustinl** [comment]
Hi @bahlo, to prevent create a duplicated issue, I'm seeing some requests to non-existents paths like `/wordpress` `/wp` `/old` `/new` `/2020` etc.

This is something related to this issue?

Thanks!

**Comment by schehata** [comment]
> Hi @bahlo, to prevent create a duplicated issue, I'm seeing some requests to non-existents paths like `/wordpress` `/wp` `/old` `/new` `/2020` etc.
> 
> This is something related to this issue?
> 
> Thanks!

those are probably bots or web crawlers maybe trying to access those routes that don't exist on your app, I believe its not related to `next-axiom`.

**Comment by bahlo** [comment]
@jerang do you still see this happening?

**Comment by jerang** [comment]
I am still seeing it and noticed a trend; seems to happen every 3 days at mid night. I don't have any automated deployments or builds so curious if that helps.
