### ISSUE TITLE
403 Forbidden error

### ISSUE THREAD

**Issue by heymartinadams** [axiomhq/next-axiom#53]
I’m receiving a `403` error in production (“message”: “Forbidden”) and am wondering if it’s because I didn’t add an API token.

Following your [next-axiom](https://github.com/axiomhq/next-axiom#get-started) instructions, I also added the `NEXT_PUBLIC_AXIOM_INGEST_ENDPOINT` to my project so that it points to a custom dataset. However, **where/how do I add the corresponding API token** so that the ingest endpoint can be accessed?

Since this is a custom dataset, I don’t have the Vercel integration installed via the Vercel dashboard.

**Comment by heymartinadams** [comment]
My company has to projects — with a single Vercel integration, they get dumped into the same datastream.

**Comment by bigint** [comment]
+1 we need this without connecting to vercel 🙏🏼

**Comment by bahlo** [comment]
Closing this for #65 🙌
