### ISSUE TITLE
Allow sending logs and web vitals from non-production deployments

### ISSUE THREAD

**Issue by nickrttn** [axiomhq/next-axiom#55]
👋 

We would like to be able to send logs and web vitals from non-production Next.js deployments on Vercel. 

Our use case is a canary deployment that we would like to open up to users for early feedback and testing. We would ideally receive logs and web vitals from that deployment so we can compare them with our production deployment and spot issues sooner rather than later.

Is this something you would consider supporting?

**Comment by bahlo** [comment]
Hey @nickrttn, enabling the `NEXT_PUBLIC_AXIOM_INGEST_ENDPOINT` env on staging deployments as well should do the trick.

Note that we currently don't attach the Vercel environment to Web-Vitals (we're working on that) so distinguishing staging vitals from prod vitals could be an issue.

Let me know if that works 🙌

**Comment by bahlo** [comment]
Closing for #65

**Comment by schehata** [comment]
@nickrttn the new version 0.16.0 has been released with this experimental feature to support non-Vercel deployments. Check it and let us know if it works the way you expected. We are all-ears for any feedback 👍
