### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '_log')

### ISSUE THREAD

**Issue by lumenwrites** [axiomhq/next-axiom#58]
Sometimes I'm seeing a popup that looks like this:
<img width="1436" alt="Screen Shot 2022-08-31 at 17 12 29" src="https://user-images.githubusercontent.com/4761235/187727505-446c75e1-b62e-43c0-b6b0-e1cb373f2c47.png">

<img width="719" alt="Screen Shot 2022-08-31 at 17 13 23" src="https://user-images.githubusercontent.com/4761235/187728601-14a6e8af-106c-49d5-a8d5-b21417588dc1.png">

And there's no way for me to know where this error is coming from, or what's causing this.

There should probably be a more meaningful error message that would help people understand what's going on.

But meanwhile - can you help me figure out how to find the source of the problem and fix it?

**Comment by lumenwrites** [comment]
Hmm... Looks like this is triggered when an axios request throws any kind of error. So this line triggers it:
```
    await axios.post("123", {})
```

Very weird and unexpected. If there's no `await` in front of axios, this error doesn't pop up.

Either way, whatever's going on with this issue, that makes it extremely difficult to debug things.

**Comment by schehata** [comment]
hmm, this is weird. not sure whats happening, but I am guessing when axios throws an error, next-axiom captures that and tries to send the log to axiom, but somehow `this` context in our logger becomes `undefined`. which next-axiom version are you using?

**Comment by schehata** [comment]
@lumenwrites I tried to reproduce the issue by using axios to call an invalid url, but I saw a normal 404 error. can you maybe provide an example that could reproduce the issue or some insight on your setup.

**Comment by schehata** [comment]
@lumenwrites haven't heard back from you for a while, I will close this issue now but please let me know if this is still happening. thx.
