### ISSUE TITLE
[Q&A] Where do I put my API token?

### ISSUE THREAD

**Issue by zanzlender** [axiomhq/next-axiom#62]
I just started using Axiom and next-axiom and I'm a little lost... So any help is appreciated 👍

From the docs I found the ingest api url should be like: ```https://cloud.axiom.co/api/v1/datasets/$DATASET_NAME/ingest```. However, I'm getting status 403, so my question is where do I need to put my API token? Just in the .env file or somewhere else?

**Comment by bahlo** [comment]
Hey @zanzlender, do you use Vercel? If yes, this is all done automatically for you after installing the integration at https://vercel.com/integrations/axiom

**Comment by raimondlume** [comment]
Same question for me - I'm planning on using `next-axiom` without Vercel (a standalone deployment on [Railway](https://railway.app)

Does `next-axiom` support non-Vercel deployments? If so, then the same question as @zanzlender.

**Comment by zanzlender** [comment]
@bahlo Sorry forgot to mention that I'm self hosting.

**Comment by schehata** [comment]
@raimondlume in the mean time we currently support running it on vercel only.

**Comment by raimondlume** [comment]
@schehata Gotcha! Is non-Vercel deployment support in the roadmap for `next-axiom` or is this Vercel only?

**Comment by bahlo** [comment]
@raimondlume We're currently exploring ways to make web-vitals and logs work on non-Vercel deployments, stay tuned 🙌

**Comment by bahlo** [comment]
Closing for #65

**Comment by schehata** [comment]
the new version 0.16.0 has been released with this experimental feature to support non-Vercel deployments. Check it and let us know if it works the way you expected. We are all-ears for any feedback 👍
