### ISSUE TITLE
Make web-vitals and logs work without Vercel

### ISSUE THREAD

**Issue by bahlo** [axiomhq/next-axiom#65]
People want to use this library but are either self-hosting or don't use Vercel (#62, #55).

The idea is to make it work by providing an API token with ingest permission and using that to ingest web-vitals and logs.

**Comment by opti21** [comment]
Hello! Just curious what is the timeline on this?

**Comment by schehata** [comment]
@opti21 the new version 0.16.0 has been released with this experimental feature to support logging on non-Vercel deployments.
