### ISSUE TITLE
with() should flush with the request logger

### ISSUE THREAD

**Issue by bahlo** [axiomhq/next-axiom#73]
If you create a new logger by running `req.log.with({ … })`, it won’t get flushed at the end of the request, but it should.

**Comment by schehata** [comment]
why `req.log.with({ … })` is different? it returns an instance of the logger with `autoFlush = true`.

**Comment by bahlo** [comment]
Yes, but `withAxiom` will only flush the parent logger (e.g. [here](https://github.com/axiomhq/next-axiom/blob/686f164dc929eb45a0edb9cd75311f2f401dfd4b/src/withAxiom.ts#L123)), we need to keep track of child loggers to flush all of them.

**Comment by schehata** [comment]
@bahlo This has been addressed in the new version `0.16.0`, now `flush()` will loop over the sub-loggers and flush all of them.
