### ISSUE TITLE
Logging on non-Nextjs frontend? 

### ISSUE THREAD

**Issue by mysteryhobo** [axiomhq/next-axiom#77]
My company has a NextJS web app running on Vercel, We also have a Chrome Extension version with duplicate front-end code utilizing the same api backend.

Would we be able to use the your logging functionality on both front-end implementations? (Assuming we set the correct environment variables for the Chrome extension in production)

**Comment by schehata** [comment]
I think it should work just fine. on the other hand, we are working on tweaking next-axiom to work on other/generic platforms as well. You can keep an eye on this PR (#67), its almost ready, and a new version will be released. When its ready, you will be able to use an API token for the chrome extension.

**Comment by mysteryhobo** [comment]
That's great! Thanks for the update, I'll keep an eye out for the new version 😄

**Comment by schehata** [comment]
@mysteryhobo the new version `0.16.0` has been released with this experimental feature to support non-Vercel deployments. Check it and let us know if it serves the purpose you wanted. We are all-ears for any feedback 👍
